version: '2'
services:
    datahubapplication-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/DATAHUBApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=DATAHUBApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
